// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools 2015 v1.7.160
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VuePack
{
    static class Vsix
    {
        public const string Id = "6ac8e91a-ade2-4e25-a8e1-a779dd6aeca3";
        public const string Name = "Vue.js Pack";
        public const string Description = "Contains HTML Intellisense and code snippets for the Vue.js JavaScript library";
        public const string Language = "en-US";
        public const string Version = "1.0.1";
        public const string Author = "Mads Kristensen";
        public const string Tags = "vue.js, snippets, javascript";
    }
}
